# Site settings
title: Steve-Emilie Love Forever
email: steveemilieamour@gmail.com
description: This is our house of love
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:steve-emilie

# Build settings
markdown: kramdown
