# Site settings
title: "SNEILY"
email: "steveemilieamour@gmail.com"
description: "steve and emilie, I LOVE YOU"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: 

# Build settings
markdown: kramdown
